# Generated by Django 2.1.5 on 2020-08-19 14:34

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200819_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to=frontend.models.content_file_user),
        ),
    ]
