# Generated by Django 2.1.5 on 2020-08-19 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_city_workindustry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loan_term', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_security', models.CharField(blank=True, max_length=50, null=True)),
                ('co_borrower', models.CharField(blank=True, max_length=60, null=True)),
                ('income_type', models.CharField(blank=True, max_length=50, null=True)),
                ('income_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('income_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('dependents', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.City')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.WorkIndustry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
