# Generated by Django 2.1.5 on 2020-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
