# Generated by Django 2.1.5 on 2020-08-20 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200820_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('borrow_term', models.IntegerField(blank=True, default=0, null=True)),
                ('issuance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('loan_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('effective_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('monthly_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Loan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
