# Generated by Django 2.1.5 on 2020-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20200821_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbid',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanbid',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
