# Generated by Django 2.1.5 on 2020-08-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_loanattach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
